# Subject Metadata used for grabbing information 
# Jeremy Delahanty Februrary 2022
subject_id: "A000"
subject_alias: "best-mouse"
ear_tag:
  l_ear: true
  r_ear: false
ear_notch:
  l_ear: false
  r_ear: false
# Cage IDs MUST be the barcode for the cage
cage_id: 0123456
# Cage Alias is whatever the experimenter likes to refer the cage as
cage_alias: "cage-alias"
# Date of birth in YYYMMDD format
dob: "20220205"
# Descriptions
description: "Mouse Description"
genotype: "HET DAT Cre"
sex: "M"
species: "Mus Musculus"
strain: "C57BL/6J"
# Surgeries are organized by date
surgery:
  "20210924":
    surgeon: "Jeremy Delahanty"
    start_time: "10:00"
    end_time: "11:00"
    stereotax: "Delta"
    anesthetic: "Isoflurane"
    skull_position:
      bregma: -0.02
      lambda: -0.02
      level_left: -0.01
      level_right: -0.01
    headplate:
      num_screws: 1
      skull_hashing: true
    grin_implant:
      target: "mPFC"
      hemisphere: "R"
      type: "Proview"
      dims: [1, 4]
      supplier: "Inscopix"
      ap: 1.90
      ml: 0.45
      dv: -2.18
      angle: null
      notes: "None"
    brain_injections:
      gcamp:
        target: "mPFC"
        hemisphere: "R"
        virus: "AAV8"
        promoter: "promoter"
        opsin: null
        fluorophore: "jGCaMP7f"
        fluorophore_excitation_lambda: 482.5
        fluorophore_emission_lambda: 513.0
        supplier: "The Salk Institute for Biological Studies"
        description: "Calcium Sensitive Green Fluorescent Indicator"
        lot: null
        ap: 1.90
        ml: 0.45
        dv: -2.20
        angle: null
        # Volume in nL
        volume: 300
        # Rate in nL/min
        rate: 100.0
        # Bevel Direction: Away from you is 0 degrees
        bevel: 90
      chr:
        target: "VTA"
        hemisphere: "R"
        virus: "AAV8"
        promoter: "hSyn"
        cre: "FLEX"
        flp: null
        opsin: "chrimsonR"
        opsin_excitation_lambda: 100.0
        fluorophore: "tdTomato"
        fluorophore_excitation_lambda: 482.5
        fluorophore_emission_lambda: 581.0
        supplier: "Supplier"
        description: "description"
        lot: null
        ap: -3.30
        ml: 0.35
        dv: -4.05
        angle: null
        # Volume in nL
        volume: 700.0
        # Rate in nL/min
        rate: 100.0
        # Bevel Direction
        bevel: 180
    analgesics:
      buprinex:
        route: "IP"
        location: "abdomen"
        # Dosages are in mg/kg
        dose: 1.0
        # Volumes here in mL
        volume: 2.0
      lidocaine:
        route: "SQ"
        location: "scalp"
        dose: null
        volume: 0.5
      loxicam:
        route: "IP"
        location: "abdomen"
        # Dosages are in mg/kg
        dose: 5.0
        volume: 0.5
    fluids:
      ringers:
        route: "IP"
        location: "abdomen"
        percent: 20.0
        volume: 1.0

status:
  alive: true
  time_of_death: null
  death_notes: null
